apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-db
  namespace: music-app
spec:
  selector:
    matchLabels:
      app: music-db
  template:
    metadata:
      labels:
        app: music-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: music-db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: music-db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: music-db-secret
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              value: musicdb
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: music-db-pvc
