apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: music-web-ingress
  namespace: music-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: music.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: music-web
            port:
              number: 80
