apiVersion: v1
kind: Secret
metadata:
  name: music-db-secret
  namespace: music-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Um9vdFBhc3MxMjMh
  MYSQL_PASSWORD: Q2hhbmdlTWUxMjMh
  MYSQL_USER: YXBwX3VzZXI=
